### ISSUE TITLE
Unet 내 num_groups parameter 통합

### ISSUE THREAD

**Issue by gih0109** [jungwonguk/KD-Font#33]
## 개요

Unet class parameter 로 `num_groups` 추가 및 하위 class parameter 통합

## 내용

현재 num_groups parameter 는 `BasicBlock` class 의 parameter 에 존재하며, 

`ResBlock` class 에만 전달되고 'TrasformerBlock` class 에는 전달되지 않는다. 

이를 통합하여 `Unet` class 에 `num_groups` parameter 로 모든 group_norm 의 num_group 을 조작할 수 있도록 수정하는 것이 목표

## TODO
- [ ] TrasformerBlock 의 class parameter 로 num_groups 추가
- [ ] BasicBlock 에서 num_groups가 TransformerBlock 으로 전달되게 수정
- [ ] Unet class 에 num_groups parameter 추가 및 수정
